@startuml

Transform <|-- Geom2D
Geom2D <|-- Surface
Fill <|-- Surface

Surface <|-- Disk
Surface <|-- Polygon
Surface <|-- Rectangle

PointsArray <|-- ReallocatablePointsArray
ReallocatablePointsArray <|-- Polygon

Rectangle <|-- Square
Transform <|-- PointsArray

@enduml
